[package]
name = "rdbc"
description = "Rust DataBase Connectivity (RDBC) API"
version = "0.1.6"
authors = ["Andy Grove <andygrove73@gmail.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
