[package]
name = "rdbc"
description = "Rust DataBase Connectivity (RDBC) API"
version = "1.0.0"
authors = ["Andy Grove <andygrove73@gmail.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
